<html> 
    <head> 
        <title>Uso de Librerias y Funciones</title> 
    </head> 
    <body> 
        <?php 
            function CabeceraPagina() { 
        ?>
                <p style="font-size: 1.5em;">Esta cabecera estara en todas sus paginas.</p> 
                <hr> 
        <?php
            }

            function PiePagina() { 
        ?> 
                <hr>
                <p style="font-size: 1em;">Este es el pie de pagina</p>
                Autor: Joaquin Gracia 
        <?php 
            } 
        ?> 

        <div>
            <a href="ejercicio_23pag1.php"><button>Página 1</button></a>
            <a href="ejercicio_23pag2.php"><button>Página 2</button></a>
        </div>
    </body> 
</html>